FROM python:<%= image.vars['python_version'] %>-alpine

ARG IMPACKET_VERSION=<%= image.vars['impacket_version'] %>

<%= snippet('labels', binding) -%>

RUN apk update \
    && apk upgrade \
    && apk cache clean \
    && pip install --no-cache-dir impacket==${IMPACKET_VERSION} \
    && find /usr/local/bin -name "*.py" ! -name "changepasswd.py" -delete \
    && find /usr/local/lib -name "*.pyc" -delete \
    && find /usr/local/lib -name "__pycache__" -type d -exec rm -rf {} + \
    && rm -rf /root/.cache \
    && adduser -D -u <%= image.vars['user_uid'] %> <%= image.vars['user_name'] %>

USER <%= image.vars['user_name'] %>

ENTRYPOINT ["changepasswd.py"]
